### ISSUE TITLE
Is there anyway to disable italics for strings?

### ISSUE THREAD

**Issue by Ashik80** [jasonm23/emacs-theme-kanagawa#1]
I have these options set to disable italics but i could not find an option about the strings.
```
(setq kanagawa-theme-comment-italic nil)
(setq kanagawa-theme-keyword-italic nil)
```

Right now i'm overriding the string font face like this.
```
(setq font-lock-string-face '((t
  (:slant normal :foreground "#98BB6C"))))
```

Is ther an option to disable italics for strings?
I'm new to emacs so maybe i'm doing something wrong. Or is this fine?

**Comment by jasonm23** [comment]
> I have these options set to disable italics but i could not find an option about the strings.

```elisp
(setq kanagawa-theme-comment-italic nil)
(setq kanagawa-theme-keyword-italic nil)
```

Does this work?

I must say, these vars are not defined by the theme, If those `setq`s work, I'd be surprised! (BTW, you can use one `setq` to set multiple vars:

```elisp
(setq 
   kanagawa-theme-comment-italic nil
   kanagawa-theme-keyword-italic nil)
```
(whitespace here is just for readability.)


As far as I know, in all cases you'd need to change the face settings themselves.

Change face settings when you load any theme, use `advice-add` for example:

```elisp
(advice-add #'load-theme 
    :after 
    (lambda (&rest _) 
      (set-face-italic 'font-lock-string-face nil)))
```

`font-lock-string-face` (check the other `font-lock-...` faces for general theming)

**Comment by jasonm23** [comment]
BTW 

> I'm new to emacs 

So let me say, congrats, it's worth it, but it is a lot to learn.

**Comment by Ashik80** [comment]
> Does this work?
>
> I must say, these vars are not defined by the theme, If those setqs work, I'd be surprised!

Yes! It does. I thought this was defined by the theme.

So it makes sense that I have to set the italic font separately.

I was wrong about this though
```
(setq font-lock-string-face '((t
  (:slant normal :foreground "#98BB6C"))))
```
this does not work. I had to use customize to actually disable italic strings. But this solved my issue. I'll close the issue now.

> So let me say, congrats, it's worth it, but it is a lot to learn.

Thank you! I'm really learning a lot and loving it

**Comment by jasonm23** [comment]
Glad you figured it out, good luck with your Emacs journey.
